apiVersion: apps/v1
kind: Deployment
metadata:
  name: descuento-deployment
  labels:
    app: descuento-deployment
spec:
  selector:
    matchLabels:
      app: descuento-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: descuento-deployment
    spec:
      containers:
        - name: descuento
          image: isisi/descuento
          ports:
            - containerPort: 8094