apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-deployment
  labels:
    app: reportes-deployment
spec:
  selector:
    matchLabels:
      app: reportes-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reportes-deployment
    spec:
      containers:
        - name: reportes
          image: isisi/reportes
          ports:
            - containerPort: 8093